on: pull_request

name: Coverage Report

jobs:
  build:
    name: 🧑‍🔬 Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: 🦋 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create config file and Check the coverage of the project
        uses: actions/checkout@v3
      - run: |
          echo ${{ secrets.CONFIG_JSON }} | base64 -d > assets/config.json
          flutter pub get
          dart pub global activate very_good_cli
          very_good test --coverage \
            --exclude-coverage "{**/*.g.dart,**/*.freezed.dart,**/entities/**,**/*_state.dart,**/core/**,**/providers.dart,**/file_service.dart,**/backend_api_base.dart}" \
            --min-coverage 80
