on: pull_request

name: Coverage Report

jobs:
  xpeho_workflows_flutter_coverage:
    uses: XPEHO/Xpeho-Workflows/.github/workflows/coverage.yaml@fix/workflows
    with:
      FLUTTER_VERSION: '3.13.1'
      MIN_COVERAGE: 80