on: pull_request

name: Flutter Test
jobs:
  build:
    name: Flutter pub get, format, analyze, and test
    runs-on: ubuntu-latest

    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create firebase config file
        uses: actions/checkout@v3
      - run: |
          echo ${{ secrets.FIREBASE_CONFIGURATION }} | base64 -d > lib/firebase_options.dart
          echo ${{ secrets.CONFIG_JSON }} | base64 -d > assets/config.json

      - name: Flutter pub get, format, analyze, and test
        run: |
          dart format lib/firebase_options.dart
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze
          flutter test
