name: SonarQube Scan

on:
  push:
    branches:
      - main
      - chore/sonar

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
            echo ${{ secrets.FIREBASE_CONFIGURATION }} | base64 -d > lib/firebase_options.dart
            echo ${{ secrets.CONFIG_JSON }} | base64 -d > assets/config.json
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: Run tests with coverage
        run: |
          # Download dependencies 
          flutter pub get 
          # Run analysis
          flutter analyze
          # Run tests without user feedback regeneration tests.output and coverage/lcov.info
          flutter test --machine --coverage > tests.output
      - name: Sonar-scanner
        env:
          SONAR_SCANNER_VER: sonar-scanner-cli-4.8.0.2856-linux
          SONAR_SCANNER_PATH: sonar-scanner-4.8.0.2856-linux/bin
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip

          $SONAR_SCANNER_PATH/sonar-scanner -v
          $SONAR_SCANNER_PATH/sonar-scanner \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}