name: SonarQube Scan

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: true
        default: "Manually triggered"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo ${{ secrets.FIREBASE_CONFIGURATION }} | base64 -d > lib/firebase_options.dart
          echo ${{ secrets.CONFIG_JSON }} | base64 -d > assets/config.json
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: "stable"
      - name: Run tests with coverage
        run: |
          # Download dependencies 
          flutter pub get 
          # Run analysis
          flutter analyze
          # Run tests without user feedback regeneration tests.output and coverage/lcov.info
          # See https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/test-coverage/dart-test-coverage/#adding-coverage-to-your-build-process
          flutter test --coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
